// `npm run i18n`: rewrites web/src/i18n/en.ts from the t('…'), say('…') (stageText.ts) and <T k={'…'}> calls in web/src, and lists what the
// German dictionaries miss or keep for nothing. `--check` changes nothing and fails when en.ts is out of date (the
// unit test runs the same scan). After adding UI text: run it, then translate the new keys in de.ts / de.client.ts
// (the typecheck names every missing one).
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const WEB = path.join(ROOT, 'web/src');
const EN = path.join(WEB, 'i18n/en.ts');

const STRING = String.raw`(?:'((?:[^'\\]|\\.)*)'|"((?:[^"\\]|\\.)*)")`;
const CALLS = [String.raw`(?<![\w.])(?:t|say)\(\s*${STRING}`, String.raw`<T\s+k=\{\s*${STRING}\s*\}`, String.raw`<T\s+k=${STRING}`].map(
  (re) => new RegExp(re, 'g'),
);
const unquote = (s: string) => s.replace(/\\(.)/g, (_, c: string) => (c === 'n' ? '\n' : c));
const text = (m: RegExpMatchArray) => unquote((m[1] ?? m[2]) as string);

function sources(dir: string): string[] {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) return sources(p);
    // the dictionaries themselves hold keys, not calls
    return /\.tsx?$/.test(e.name) && !/^(en|de|de\.client)\.ts$/.test(e.name) ? [p] : [];
  });
}

/** Every key the code uses, sorted. */
export function usedKeys(): string[] {
  const keys = new Set<string>();
  for (const f of sources(WEB)) {
    const code = fs.readFileSync(f, 'utf8');
    for (const re of CALLS) for (const m of code.matchAll(re)) keys.add(text(m));
  }
  return [...keys].sort((a, b) => a.localeCompare(b, 'en'));
}

// Biome's style: double quotes when that saves escaping a single quote.
const quote = (s: string) => {
  const body = s.replace(/\\/g, '\\\\').replace(/\n/g, '\\n');
  return s.includes("'") && !s.includes('"') ? `"${body}"` : `'${body.replace(/'/g, "\\'")}'`;
};

export function catalog(keys: string[]): string {
  return `// Generated by \`npm run i18n\` from the t() / <T> calls in web/src: every English text the UI shows, in order.
// Don't edit by hand; translate new keys in de.ts (owner app, "du") or de.client.ts (client pages, "Sie").
export const EN = [
${keys.map((k) => `  ${quote(k)},`).join('\n')}
] as const;

export type Key = (typeof EN)[number];
`;
}

/** The keys a German dictionary file defines. */
export function definedKeys(file: string): string[] {
  const code = fs.readFileSync(file, 'utf8');
  // quoted keys, and the ones Biome leaves bare because they are plain identifiers (Actions: …)
  return [...code.matchAll(new RegExp(String.raw`^\s+(?:${STRING}|([A-Za-z_$][\w$]*)):`, 'gm'))].map((m) => (m[3] ?? text(m)) as string);
}

if (import.meta.main) {
  const keys = usedKeys();
  const next = catalog(keys);
  const now = fs.existsSync(EN) ? fs.readFileSync(EN, 'utf8') : '';
  if (process.argv.includes('--check')) {
    if (now !== next) {
      console.error('web/src/i18n/en.ts is out of date: run `npm run i18n`.');
      process.exit(1);
    }
  } else if (now !== next) fs.writeFileSync(EN, next);
  const de = ['de.ts', 'de.client.ts'].map((f) => path.join(WEB, 'i18n', f)).filter((f) => fs.existsSync(f));
  const defined = new Set(de.flatMap(definedKeys));
  const missing = keys.filter((k) => !defined.has(k));
  const unused = [...defined].filter((k) => !keys.includes(k));
  console.log(`${keys.length} keys · ${missing.length} without German · ${unused.length} German entries nothing uses`);
  for (const k of missing) console.log(`  missing: ${k}`);
  for (const k of unused) console.log(`  unused:  ${k}`);
}
