# The Contributor License Agreement (CLA.md) on pull requests: a contributor signs once, with one comment, and the
# check stays green on every later pull request. Signatures are kept on the cla-signatures branch (main is protected).
# pull_request_target runs this file as it is on main, with a token that may write the signature; it never checks out
# or runs the pull request's code. The maintainer and bots are on the allowlist.
name: CLA

on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, synchronize, reopened, closed]

permissions:
  actions: write
  contents: write
  pull-requests: write
  statuses: write

jobs:
  cla:
    name: CLA signed
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: github.event_name == 'pull_request_target' || (github.event.issue.pull_request && (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA'))
    steps:
      - uses: contributor-assistant/github-action@ca4a40a7d1004f18d9960b404b97e5f30a505a08 # v2.6.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          path-to-signatures: signatures/cla.json
          path-to-document: https://github.com/lampo-vr/lampo/blob/main/CLA.md
          branch: cla-signatures
          allowlist: vll711,dependabot[bot],github-actions[bot]
          lock-pullrequest-aftermerge: false
